# Generated by Django 3.2.9 on 2022-01-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('Break Fast', 'Break Fast'), ('Lunch And Dinner', 'Lunch And Dinner'), ('Snack', 'Snack')], default='Lunch And Dinner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('date_of_record', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='foods/')),
                ('category', models.ManyToManyField(related_name='foods', to='foods.Category')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.meal')),
            ],
        ),
    ]
