# Generated by Django 3.2.9 on 2021-12-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('online_food', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date_of_register', models.DateField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='accounts.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='online_food.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='online_food.restaurant')),
            ],
        ),
    ]
