# Generated by Django 3.2.9 on 2021-12-26 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('bf', 'Break Fast'), ('ld', 'Lunch And Dinner'), ('sn', 'Snack')], default='ld', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='meal',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('date_of_record', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='foods/')),
                ('category', models.ManyToManyField(related_name='foods', to='online_food.Category')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='online_food.meal')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='online_food.meal'),
            preserve_default=False,
        ),
    ]
