# Generated by Django 3.2.9 on 2021-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0004_auto_20211226_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='foods',
            field=models.ManyToManyField(related_name='branches', to='online_food.Food'),
        ),
    ]
