# Generated by Django 3.2.9 on 2021-12-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff'),
        ('online_food', '0006_auto_20211226_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('customers_status', models.CharField(choices=[('a', 'added'), ('c', 'confirmed'), ('s', 'is sending'), ('d', 'delivered')], default='a', max_length=1)),
                ('restaurnat_status', models.CharField(choices=[('r', 'recorded'), ('p', 'in progress'), ('d', 'delivered')], default='r', max_length=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer')),
                ('menu', models.ManyToManyField(related_name='orders', to='online_food.Menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='online_food.branch')),
            ],
        ),
    ]
