# Generated by Django 3.2.9 on 2021-12-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0008_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurnat_status',
            new_name='restaurnt_status',
        ),
    ]
