# Generated by Django 3.2.9 on 2021-12-30 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0009_rename_restaurnat_status_order_restaurnt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='number_of_existance',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('number_of_existance', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuItems', to='online_food.food')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='item',
            field=models.ManyToManyField(related_name='menus', to='online_food.MenuItem'),
        ),
    ]
