# Generated by Django 3.2.9 on 2021-12-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0010_auto_20211230_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='menu',
        ),
        migrations.AddField(
            model_name='branch',
            name='menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='online_food.menu'),
        ),
    ]
