# Generated by Django 3.2.9 on 2022-01-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0016_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurnt_status',
            new_name='restaurant_status',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
