# Generated by Django 3.2.9 on 2022-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0017_auto_20220105_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('Break Fast', 'Break Fast'), ('Lunch And Dinner', 'Lunch And Dinner'), ('Snack', 'Snack')], default='Lunch And Dinner', max_length=20),
        ),
    ]
