# Generated by Django 3.2.9 on 2022-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0018_alter_meal_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order_time',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
