# Generated by Django 3.2.9 on 2022-01-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0019_menuitem_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
