# Generated by Django 3.2.9 on 2022-01-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('online_food', '0022_auto_20220106_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='meal',
        ),
        migrations.AlterField(
            model_name='branch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='foods.category'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='foods.meal'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuItems', to='foods.food'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
