# Generated by Django 3.2.9 on 2022-01-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_food', '0023_auto_20220108_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='online_food.menu'),
        ),
    ]
