# Generated by Django 3.2.9 on 2022-01-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='customers', to='accounts.Address'),
        ),
    ]
