# Generated by Django 3.2.9 on 2022-01-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
