# Generated by Django 3.2.9 on 2022-01-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_address_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
